import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import NextAuthWarper from "@/lib/next.auth.wrapper";
import '@ant-design/v5-patch-for-react-19';
import ClientWrapper from "@/lib/next.skip.error.antd";
import { NotificationProvider } from "@/lib/notificationProvider";
import { App, ConfigProvider, theme } from "antd";
import "leaflet/dist/leaflet.css";
import { SessionProvider } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/auth";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <NextAuthWarper session={session}>
            {/* <ClientWrapper> */}
            <NotificationProvider>
              <ConfigProvider theme={{ algorithm: theme.defaultAlgorithm }}>
                <App>
                  {children}
                </App >
              </ConfigProvider>

            </NotificationProvider>
            {/* </ClientWrapper> */}
          </NextAuthWarper>
        </AntdRegistry>
      </body>
    </html>
  );
}
